apiVersion: v1
kind: Service
metadata:
  name: my-config-app-service
spec:
  selector:
    app: my-config-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
